 nb @startuml
class Usuario {
  nombre : String
  id : int
  password : String
  fechaNacimiento : Date
  foto : String
  email : String
  valoracion : float
  valoraciones : List<flloat>
  Usuario(nombre, password, fechaNacimiento, foto, email)
  iniciarSesion(email,password) : bool
  recuperarPassword(email) : bool
  modificarPerfil(nombre, password, fechaNacimiento, foto, email) : bool
  eliminar(password) : bool
  seguirUsuario(usuario) : bool
  recibirValoracion(valoracion) : bool
  recibirComentario(comentario) : bool
  crearEvento(evento) : bool
  modificarEvento(evento) : bool
  toJson() : JSONObject
}

class Evento {
  id : int
  nombre : String
  ubicacion : String
  fecha : Date
  host : Usuario
  valoracion : float
  valoraciones : List<float>
  etiquetas : List<String>
  Evento(nombre, ubicacion, fecha, host, etiquetas)
  modificar(nombre, ubicacion, fecha, host, etiquetas) : bool
  recibirComentario(comentario) : bool
  recibirValoracion(valoracion) : bool
  añadirParticipante(participante) : bool
  eliminarParticipante(participante) : bool
  eliminar() : bool
  añadirPublicacion(publicacion) : bool
  toJson() : JSONObject
}

class Publicacion {
  autor : Usuario
  fecha : Date
  imagenes : List<String>
  contenido : String
  Publicacion(autor, fecha, imagenes, contenido)
  eliminar() : bool
  toJson() : JSONObject
}

class Comentario {
  autor : Usuario
  fecha : Date
  contenido : String
  Comentario(autor, fecha, contenido)
  toJson() : JSONObject
}

Usuario "0" *--> "*" Evento : eventos
Evento "1" --> "1" Usuario : host
Evento "0" *--> "*" Publicacion : publicaciones
Evento "1" *--> "*" Usuario : participantes
Evento "0" *--> "*" Comentario : comentarios
Usuario "0" *--> "*" Comentario : comentarios
@enduml